"""creating Removing The Resume table - Third Migartion

Revision ID: 543af1c686ec
Revises: 5b2aa04c829f
Create Date: 2026-10-03 00:26:06.031572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543af1c686ec'
down_revision: Union[str, Sequence[str], None] = '5b2aa04c829f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('public_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resumes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###
